cmd: "ant"
name: "dist"

atomCommandName: build-ant:ant

targets:

  appimage:
      cmd: "ant"
      name: "appimage"
      args:
        - appimage

  run:
      cmd: "ant"
      name: "run"
      args:
        - run

  clean:
      cmd: "ant"
      name: "clean"
      args:
        - clean
